name: Update Akka CLI version

on:
  workflow_dispatch:

jobs:
  update_version:
    name: Create bump Pull Request
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/github-script/releases
      # v9.0.0
    - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3
      id: check
      with:
        script: |
          if ("${{ github.rest.issue.title }}" != "update akka" && "${{ github.event_name }}" != "workflow_dispatch") {
            console.log('Issue is not to update akka');
            return 'stop'
          } else {
            return 'build'
          }
          console.log("${{ github.event_name }}")
        result-encoding: string

    - name: Checkout
      # https://github.com/actions/checkout/releases
      # v7.0.1
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      if: steps.check.outputs.result == 'build'
      # Force fetching only latest main
      with:
        ref: 'main'

    - name: Run command
      run: python3 -m pip install requests && ./scripts/akka-script.py
      if: steps.check.outputs.result == 'build'

    - name: Create Pull Request
      # https://github.com/peter-evans/create-pull-request/releases
      # v8.1.1
      uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1
      if: steps.check.outputs.result == 'build'
      with:
        title: Update akka CLI version
        branch-suffix: short-commit-hash
        body: Update akka CLI to latest stable version
        delete-branch: true
        commit-message: "feat(cli): update akka CLI to the latest stable version"
        author: "GitHub <noreply@github.com>"
